#! /bin/sh

set -e

version=`./configure -version 2>/dev/null`
destdir="pxp-$version"

echo "Ensure the gensrc-pre lexers are up to date!"

mkdir -p packages
rm -rf "packages/$destdir"
makepkg -spec pxp.files -intree . -outtree "packages/$destdir"
touch "packages/$destdir/gensrc/pxp-wlex-utf8/gen_done"
(cd packages; tar czf "$destdir.tar.gz" "$destdir")

