#! /bin/sh

set -e

(cd reader && ./test_reader)
(cd reader && ./test_rewritten_reader)
(cd canonxml && ./run_canonxml)
(cd write && ./run_write)
(cd codewriter && ./run_codewriter)
(cd negative && ./run_negative)
(cd dynamic && ./run)
(cd lex && ./run)
