all:
	$(MAKE) -C m2parsergen
	$(MAKE) -C ucs2_to_utf8

clean:

CLEAN: clean
	$(MAKE) -C m2parsergen CLEAN
	$(MAKE) -C ucs2_to_utf8 CLEAN

distclean:
	$(MAKE) -C m2parsergen distclean
	$(MAKE) -C ucs2_to_utf8 distclean
