# Such that we have all the definitions:
include Makefile

OCAMLC_OPTIONS   = -I ../pxp-engine
OCAMLOPT_OPTIONS = -I ../pxp-engine
PACKAGES = netstring

pxp_lex_iso88591.cma: $(OBJ) pxp_lex_link_iso88591.cmo 
	$(OCAMLC) -o pxp_lex_iso88591.cma -a $(OBJ)

pxp_lex_iso88591.cmxa: $(XOBJ) pxp_lex_link_iso88591.cmx
	$(OCAMLOPT) -o pxp_lex_iso88591.cmxa -a $(XOBJ)

include depend

*.ml: ../pxp-engine/pxp_types.cmi ../pxp-engine/pxp_lexer_types.cmi
