#! /bin/sh

test_sample () {
    file="$1"
    printf "%s" "Testing $file... "
    ./test_write -in "$file" >out1
    ./test_write -in out1    >out2
    ./test_write -in out2    >out3
    if cmp out1 out3; then
	echo "OK"
    else
	echo "FAILED"
    fi
}


test_sample "sample001.xml"

# TODO: a test for namespaces.
