#! /bin/sh
#
# $Id: collect_files,v 1.1 2000/07/27 21:07:26 gerd Exp $
# ----------------------------------------------------------------------
#
# usage: collect_files file ...
#
# Prints the names of the files passed as arguments which actually
# exist and are regular files.

for x in "$@"; do
    if [ -f "$x" ]; then
	echo "$x"
    fi
done

# ======================================================================
#
# $Log: collect_files,v $
# Revision 1.1  2000/07/27 21:07:26  gerd
# 	Initial revision.
#
