all:
	false

clean:

distclean:
	$(MAKE) -C pxp distclean
	$(MAKE) -C pxp-engine distclean
	$(MAKE) -C pxp-pp distclean

CLEAN:
	$(MAKE) -C pxp CLEAN
	$(MAKE) -C pxp-engine CLEAN
	$(MAKE) -C pxp-pp CLEAN

uninstall:
	$(MAKE) -C pxp uninstall
	$(MAKE) -C pxp-engine uninstall
	$(MAKE) -C pxp-pp uninstall
